AWSTemplateFormatVersion: '2010-09-09'
Description: 'SQS + Manifest + Glue Streaming NDJSON to Parquet Pipeline (v1.1.0 - Updated with code review fixes)'

# Version 1.1.0 Changes:
# - Added DeletionPolicy and UpdateReplacePolicy to S3 buckets
# - Added configurable file validation environment variables
# - Added lock TTL configuration
# - Enhanced alarms and monitoring

Parameters:
  ProjectName:
    Type: String
    Default: ndjson-parquet-sqs
    Description: Project name for resource naming
  
  InputBucketName:
    Type: String
    Description: S3 bucket for incoming NDJSON files
    Default: ndjson-input-sqs
  
  ManifestBucketName:
    Type: String
    Description: S3 bucket for manifest files
    Default: ndjson-manifests
  
  OutputBucketName:
    Type: String
    Description: S3 bucket for output Parquet files
    Default: parquet-output-sqs
  
  QuarantineBucketName:
    Type: String
    Description: S3 bucket for quarantined files
    Default: ndjson-quarantine
  
  MaxBatchSizeGB:
    Type: Number
    Default: 1.0
    Description: Maximum manifest batch size in GB
  
  ExpectedFileSizeMB:
    Type: Number
    Default: 3.5
    Description: Expected NDJSON file size in MB
  
  SizeTolerancePercent:
    Type: Number
    Default: 10
    Description: Allowed variance in file size (percent)
  
  GlueWorkerType:
    Type: String
    Default: G.2X
    AllowedValues: [G.1X, G.2X, G.4X, G.8X]
    Description: Glue worker type
  
  GlueNumberOfWorkers:
    Type: Number
    Default: 10
    Description: Number of Glue workers for streaming job
  
  AlertEmail:
    Type: String
    Description: Email address for alerts
    Default: magzine323@gmail.com

Resources:
  # ==================== S3 BUCKETS ====================
  
  # ==================== SQS QUEUES ====================
  
  FileEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-file-events'
      VisibilityTimeout: 900  # 15 minutes (5x Lambda timeout)
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileEventDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FileEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-file-events-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FileEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FileEventQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt FileEventQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt InputBucket.Arn

  # ==================== DYNAMODB TABLES ====================
