AWSTemplateFormatVersion: '2010-09-09'
Description: 'SQS + Manifest + Glue Streaming NDJSON to Parquet Pipeline (v1.1.0 - Updated with code review fixes)'

# Version 1.1.0 Changes:
# - Added DeletionPolicy and UpdateReplacePolicy to S3 buckets
# - Added configurable file validation environment variables
# - Added lock TTL configuration
# - Enhanced alarms and monitoring

Parameters:
  ProjectName:
    Type: String
    Default: ndjson-parquet-sqs
    Description: Project name for resource naming
  
  InputBucketName:
    Type: String
    Description: S3 bucket for incoming NDJSON files
    Default: ndjson-input-sqs
  
  ManifestBucketName:
    Type: String
    Description: S3 bucket for manifest files
    Default: ndjson-manifests
  
  OutputBucketName:
    Type: String
    Description: S3 bucket for output Parquet files
    Default: parquet-output-sqs
  
  QuarantineBucketName:
    Type: String
    Description: S3 bucket for quarantined files
    Default: ndjson-quarantine
  
  MaxBatchSizeGB:
    Type: Number
    Default: 1.0
    Description: Maximum manifest batch size in GB
  
  ExpectedFileSizeMB:
    Type: Number
    Default: 3.5
    Description: Expected NDJSON file size in MB
  
  SizeTolerancePercent:
    Type: Number
    Default: 10
    Description: Allowed variance in file size (percent)
  
  GlueWorkerType:
    Type: String
    Default: G.2X
    AllowedValues: [G.1X, G.2X, G.4X, G.8X]
    Description: Glue worker type
  
  GlueNumberOfWorkers:
    Type: Number
    Default: 10
    Description: Number of Glue workers for streaming job
  
  AlertEmail:
    Type: String
    Description: Email address for alerts
    Default: magzine323@gmail.com

Resources:
  # ==================== S3 BUCKETS ====================
  
  InputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${InputBucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt FileEventQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .ndjson
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: input-bucket-logs/
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: NDJSON Input Storage

  ManifestBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ManifestBucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldManifests
            Status: Enabled
            ExpirationInDays: 7
            Prefix: manifests/
          - Id: DeleteOldCheckpoints
            Status: Enabled
            ExpirationInDays: 7
            Prefix: checkpoints/
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Manifest Storage

  OutputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${OutputBucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      IntelligentTieringConfigurations:
        - Id: EntirePrefix
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 180
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Parquet Output Storage

  QuarantineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${QuarantineBucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireQuarantinedFiles
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Quarantine Storage

  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-logs-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Access Logging

  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${LoggingBucket.Arn}/*'
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt InputBucket.Arn

  # ==================== SQS QUEUES ====================
  
  FileEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-file-events'
      VisibilityTimeout: 900  # 15 minutes (5x Lambda timeout)
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileEventDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FileEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-file-events-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FileEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FileEventQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt FileEventQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt InputBucket.Arn

  # ==================== DYNAMODB TABLES ====================


  # ==================== IAM ROLES ====================
  
  ManifestBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-manifest-builder-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ManifestBuilderPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt FileEventQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                Resource: !Sub '${InputBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${ManifestBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:CopyObject
                Resource: !Sub '${QuarantineBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt FileTrackingTable.Arn
                  - !Sub '${FileTrackingTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                Resource: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${ProjectName}-streaming-processor'

  ControlPlaneRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-control-plane-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ControlPlanePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetJobRun
                  - glue:GetJob
                Resource:
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${ProjectName}-streaming-processor'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${ManifestBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource:
                  - !GetAtt FileTrackingTable.Arn
                  - !Sub '${FileTrackingTable.Arn}/index/*'
                  - !GetAtt MetricsTable.Arn
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref AlertTopic

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-glue-job-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueJobS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt InputBucket.Arn
                  - !Sub '${InputBucket.Arn}/*'
                  - !GetAtt ManifestBucket.Arn
                  - !Sub '${ManifestBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                Resource:
                  - !Sub '${OutputBucket.Arn}/*'
                  - !Sub '${ManifestBucket.Arn}/checkpoints/*'
                  - !Sub '${ManifestBucket.Arn}/spark-logs/*'
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'